### ISSUE TITLE
Connection takes too much time. 

### ISSUE THREAD

**Issue by jhylmb** [Vidyo/vidyo.io-connector-wpf#4]
I recorded the connection time. It tooks 1:07 or 1:08 for connection.
https://youtu.be/yK7gWGVmt_w (demo app from https://developer.vidyo.io/#/join/FuBLdtQg)
https://youtu.be/GSgg81mMBrY (wpf build using visual studio 2019)

iOS, Android(both Xamarin) works fine. 
How can I shorten the delay?

My company has a plan to make a health consult app. The users will use iOS/Android vidyo app and the consultants will use wpf vidyo app. Connection speed matters!

**Comment by jhylmb** [comment]
Thanks for your help @PassivePicasso. 

You Should right. 
I tried build/demo version each in other windows10 pc. They worked fine. The connection tooks just seconds. The problem definatly  derived from my machine configuration. 

So I tried rebooting pc, turning off Windows Defender firewall. But connection delay is still same. Could please suggest any other configuration that I could check? Thanks in advance.

**Comment by jhylmb** [comment]
Thank you very much @PassivePicasso 

I remember I had installed GoodbyeDPI(https://github.com/ValdikSS/GoodbyeDPI). It is a passive deep packet inspection blocker. I will uninstall it right now and come back to report the result.

**Comment by vtareiev** [comment]
@jhylmb , if you still haven't figured what caused the delay, then feel free to open a support ticket via emailing support@vidyo.io. We will need to take a look at VidyoClient log from that machine in order to pinpoint the problem. You can also cc me directly (vtareiev@vidyo.com) so that your request reached me directly.
However, @PassivePicasso should be right - this is definitely some network config issue on that particular machine(s).

p.s. @PassivePicasso  thanks for hopping on this thread and your advices!

**Comment by jhylmb** [comment]
@PassivePicasso  Wow you gave me a perfect solution. Uninstalling GoodbyeDPI fixed delayed connection problem. You save me a lot of time. Thank YOU!!!
